version: 2.1
orbs:
  node: circleci/node@5.0.2
  windows: circleci/windows@5.0.0

jobs:
  build:
    executor: windows/default
    steps:
      - checkout
      - run: npm install
      - run: npm run make
workflows:
  my-workflow:
    jobs:
      - build